IRC:
  SETTINGS:
    IDENTIFY: false
    NICKNAME: 'default'
    PASSWORD: 'default'
    SERVER: irc.esper.net
    PORT: 6667
  OPTIONS:
    MESSAGE_LIMIT_PER_SEC: 2
    TIMEOUT: 2000
    RETRYS: 5
    DEBUG: false
    PASS_ON_NAME: false
    ALLOW_COLORS: true
  ADMIN:
    INGAME_COMMANDS: false
    INGAME_COMMANDS_PREFIX: '.'
  FORMAT:
    MINECRAFT: '<{groupPrefix}{prefix}{name}{suffix}{groupSuffix}>: {message}'
    IRC: '<{groupPrefix}{prefix}{name}{suffix}{groupSuffix}>: {message}'
  ON_CONNECT_COMMANDS: []
  MUTED:
  - sampleuser
