name: MonsterIRC
main: org.monstercraft.irc.MonsterIRC
version: 1.53
author: Fletch_to_99
description: Using your servers IRC channel we allow communication between IRC and Ingame.
depend: [Vault]
commands:
  irc:
    description: All irc related commands. ban, mute, unmute, connect, disconnect, nick, say, reloadconfig
    usage: /irc [command] [msg]