name: MonsterIRC
main: org.monstercraft.irc.MonsterIRC
version: 1.61
author: Fletch_to_99
description: Using your servers IRC channel we allow communication between IRC and Ingame.
depend: [Vault]
softdepend: [mcMMO, TownyChat, Towny, Herochat]
commands:
  irc:
    description: IRC Commands, refer to bukkit dev page for help.
    usage: /irc [command] [msg]