name: IRC
main: org.monstercraft.irc.IRC
version: 1.0
commands:
    irc say:
        description: Sends a message to the irc.
    irc connect:
        description: Connects to the irc.
    irc disconnect:
        description: disconnects from the irc.
    irc nick:
        description: Changes the nickname within the irc.
