IRC:
  SETTINGS:
    IDENTIFY: false
    NICKNAME: 'default'
    PASSWORD: 'default'
    SERVER: 'irc.esper.net'
    SERVER_PASSWORD: ''
    PORT: 6667
  OPTIONS:
    MESSAGE_LIMIT_PER_SEC: 2
    DEBUG: false
    PASS_ON_NAME: false
    ALLOW_COLORS: true
    PART_ON_DISCONNECT: true
  ADMIN:
    INGAME_COMMANDS: false
    INGAME_COMMANDS_PREFIX: '.'
    PASS_SAY_COMMAND: false
  FORMAT:
    MINECRAFT: '&f<{groupPrefix}{prefix}{name}{suffix}{groupSuffix}&f>: {HCchannelColor}{message}'
    IRC: '{heroChatTag}: &f<{groupPrefix}{prefix}{name}{suffix}{groupSuffix}&f>: {HCchannelColor}{message}'
  ON_CONNECT_COMMANDS: []
  MUTED:
  - sampleuser
